name: web-gallery-app
services:
  minio:
      image: quay.io/minio/minio
      container_name: minio1
      user: "${UID}:${GID}"
      ports:
        - "9000:9000"
        - "9001:9001"
      environment:
        MINIO_ROOT_USER: altaf
        MINIO_ROOT_PASSWORD: GoodTime221
      volumes:
        - ${HOME}/minio/data:/data
      command: server /data --console-address ":9001"
  db:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: GoodTime221
