}Project CloudChest {
  database_type: 'MySQL'
}

Table users {
  id int [pk, increment, note: "generated by gorm"]
  first_name varchar(50) [not null]
  last_name varchar(50) [not null]
  username varchar(50) [unique, not null]
  email varchar(255) [unique, not null]
  password varchar(64) [not null]
  minio_bucket varchar(50) [not null]
  created_at datetime [not null]
  updated_at datetime
}

Table folders {
  id int [pk, increment, note: "generated by gorm"]
  user_id int [ref: > users.id]
  code varchar()
  path varchar(255) [not null]
}

Table files {
  id int [pk, increment, note: "generated by gorm"]
  user_id int [ref: > users.id]
  file_name varchar(255) [not null]
  file_size int [not null]
  file_type varchar(100) [not null]
  is_favorite bool [not null, default: 0]
}

Table folder_relationships {
  parent_id int [pk, ref: > folders.id]
  child_id int [pk, ref: > folders.id]
}

Table folder_contents {
  folder_id int [pk, ref: > folders.id]
  file_id int [pk, ref: > files.id]
}
